name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:        # Permite execução manual
  push:
    branches:
      - main                # Garante que funciona na branch correta

jobs:
  generate:
    permissions:
      contents: write       # Permissão para escrever no repositório
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg 

      - name: Criar Pasta para Output
        run: mkdir -p dist && mv dist/snake.svg dist/snake.svg

      - name: Push do Arquivo Gerado
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
